name: Build Obsidian Plugin

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Display package.json
      run: cat package.json

    - name: Install @types/node
      run: npm install --save-dev @types/node

    - name: Install dependencies
      run: npm ci

    - name: Build plugin
      run: npm run build

    - name: Create ZIP file
      run: |
        mkdir -p dist
        cp main.js manifest.json styles.css dist/
        cd dist
        zip -r ../plugin.zip .

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload plugin ZIP
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./plugin.zip
        asset_name: plugin.zip
        asset_content_type: application/zip
